package client.api;

import com.google.gson.reflect.TypeToken;
import com.mastercard.openbanking.client.ApiClient;
import com.mastercard.openbanking.client.ApiException;
import com.mastercard.openbanking.client.ApiResponse;
import com.mastercard.openbanking.client.api.CashFlowAnalyticsApi;
import com.mastercard.openbanking.client.model.ObbAnalyticsReport;
import okhttp3.Call;
import okhttp3.Request;

import java.io.File;

/**
 * OpenAPI Generator doesn't support content negotiation / fetching multiple content types.
 * See: https://github.com/OpenAPITools/openapi-generator/issues/6126
 *
 * This class extends the CashFlowAnalyticsApi class generated by OpenAPI Generator to
 * support both JSON and PDF report types.
 */
public class CustomCashFlowAnalyticsApi  extends CashFlowAnalyticsApi {

    public CustomCashFlowAnalyticsApi(ApiClient apiClient) {
        super(apiClient);
    }

    /**
     * Get a JSON report.
     */
    public ObbAnalyticsReport getObbAnalyticsJsonReport(String obbReportId) throws ApiException {
        return this.getObbAnalyticsReport(obbReportId);
    }

    /**
     * Get a PDF report.
     */
    public File getObbAnalyticsPdfReport(String obbReportId) throws ApiException {
        if (obbReportId == null) {
            throw new ApiException("Missing the required parameter 'obbReportId' when calling getObbAnalyticsPdfReport(Async)");
        }

        // Generate a regular request
        Call jsonCall = getObbAnalyticsReportCall(obbReportId, null);

        // Override the "Accept" header
        Request request = jsonCall.request()
                .newBuilder()
                .header("Accept", "application/pdf")
                .build();
        Call pdfCall = getApiClient().getHttpClient().newCall(request);

        // Get the PDF
        ApiResponse<File> pdfFile = getApiClient().execute(pdfCall, new TypeToken<File>(){}.getType());
        return pdfFile.getData();
    }
}
