/*
 * Open Banking
 * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.openbanking.client.api;

import com.mastercard.openbanking.client.ApiException;
import com.mastercard.openbanking.client.model.ErrorMessage;
import com.mastercard.openbanking.client.model.InitiatedMicroDeposit;
import com.mastercard.openbanking.client.model.MicroDepositDetails;
import com.mastercard.openbanking.client.model.MicroDepositInitiation;
import com.mastercard.openbanking.client.model.MicroDepositVerification;
import com.mastercard.openbanking.client.model.MicroDepositVerificationError;
import com.mastercard.openbanking.client.model.VerifiedMicroDeposit;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountValidationAssistanceApi
 */
@Disabled
public class AccountValidationAssistanceApiTest {

    private final AccountValidationAssistanceApi api = new AccountValidationAssistanceApi();

    /**
     * Get Micro Entries Details
     *
     * Fetch the micro entries details. &#x60;customerId&#x60; and &#x60;accountId&#x60; are the identifiers of the customer and account receiving the micro entries.    _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMicroDepositsDetailsTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        MicroDepositDetails response = api.getMicroDepositsDetails(customerId, accountId);
        // TODO: test validations
    }

    /**
     * Initiate Micro Entries
     *
     * Initiate the micro entries to customer&#39;s account.  Two random micro amounts less than a dollar each will be deposited to provided customer&#39;s account.    _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void initiateMicroAmountDepositsTest() throws ApiException {
        String customerId = null;
        MicroDepositInitiation microDepositInitiation = null;
        InitiatedMicroDeposit response = api.initiateMicroAmountDeposits(customerId, microDepositInitiation);
        // TODO: test validations
    }

    /**
     * Verify Micro Entries
     *
     * Verify the micro entries as received by customer in customer&#39;s account. Customer needs to verify the micro amounts received in customer&#39;s account. &#x60;customerId&#x60; and &#x60;accountId&#x60; are the identifiers of the customer and account  receiving the micro entries.    _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyMicroAmountDepositsTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        MicroDepositVerification microDepositVerification = null;
        VerifiedMicroDeposit response = api.verifyMicroAmountDeposits(customerId, accountId, microDepositVerification);
        // TODO: test validations
    }

}
