/*
 * Open Banking
 * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.openbanking.client.api;

import com.mastercard.openbanking.client.ApiException;
import com.mastercard.openbanking.client.model.CustomerAccount;
import com.mastercard.openbanking.client.model.CustomerAccounts;
import com.mastercard.openbanking.client.model.ErrorMessage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountsApi
 */
@Disabled
public class AccountsApiTest {

    private final AccountsApi api = new AccountsApi();

    /**
     * Delete Customer Account by ID
     *
     * Remove the given account from Finicity aggregation.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteCustomerAccountTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        api.deleteCustomerAccount(customerId, accountId);
        // TODO: test validations
    }

    /**
     * Delete Customer Accounts by Institution Login ID
     *
     * Remove from Finicity aggregation the set of accounts matching the institution login ID.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteCustomerAccountsByInstitutionLoginTest() throws ApiException {
        String customerId = null;
        String institutionLoginId = null;
        api.deleteCustomerAccountsByInstitutionLogin(customerId, institutionLoginId);
        // TODO: test validations
    }

    /**
     * Get Customer Account by ID
     *
     * Get a customer account by ID.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCustomerAccountTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        CustomerAccount response = api.getCustomerAccount(customerId, accountId);
        // TODO: test validations
    }

    /**
     * Get Customer Accounts
     *
     * Get all accounts owned by the given customer.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCustomerAccountsTest() throws ApiException {
        String customerId = null;
        String status = null;
        String accountType = null;
        CustomerAccounts response = api.getCustomerAccounts(customerId, status, accountType);
        // TODO: test validations
    }

    /**
     * Get Customer Accounts by Institution ID
     *
     * Get all active accounts owned by the given customer at the given institution.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCustomerAccountsByInstitutionTest() throws ApiException {
        String customerId = null;
        Long institutionId = null;
        CustomerAccounts response = api.getCustomerAccountsByInstitution(customerId, institutionId);
        // TODO: test validations
    }

    /**
     * Get Customer Accounts by Institution Login ID
     *
     * Get all accounts associated with the given institution login. All accounts returned are accessible by a single set of credentials on a single institution.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCustomerAccountsByInstitutionLoginTest() throws ApiException {
        String customerId = null;
        String institutionLoginId = null;
        CustomerAccounts response = api.getCustomerAccountsByInstitutionLogin(customerId, institutionLoginId);
        // TODO: test validations
    }

    /**
     * Refresh Customer Accounts
     *
     * Refresh account and transaction data for all accounts associated with the  given &#x60;customerId&#x60; with a connection to the institution.  Client apps are not permitted to automate calls to the Refresh services. Active accounts are automatically refreshed by Finicity once per day. Because many financial institutions only post transactions once per day, calling Refresh services repeatedly is usually a waste of resources and is not recommended.  Apps may call Refresh services for a specific customer when there is a specific business case for the need of data that is up to date as of the moment. Please discuss with your account manager and systems engineer for further clarification.  The recommended timeout setting for this request is 120 seconds in order to receive a response. However, you can terminate the connection after making the call the operation will still complete. You will have to pull the account records to check for an updated aggregation attempt date to know when the refresh is complete.  Note: This service is not available for all Data Access Tiers.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void refreshCustomerAccountsTest() throws ApiException {
        String customerId = null;
        CustomerAccounts response = api.refreshCustomerAccounts(customerId);
        // TODO: test validations
    }

    /**
     * Refresh Customer Accounts by Institution Login ID
     *
     * Refresh account and transaction data for all accounts associated with a given &#x60;institutionLoginId&#x60; with a connection to the institution.  Client apps are not permitted to automate calls to the Refresh services. Active accounts are automatically refreshed by Finicity once per day. Because many financial institutions only post transactions once per day, calling Refresh repeatedly is usually a waste of resources and is not recommended.  Apps may call Refresh services for a specific customer when there is a specific business case for the need of data that is up to date as of the moment. Please discuss with your account manager and systems engineer for further clarification.  The recommended timeout setting for this request is 120 seconds in order to receive a response. However, you can terminate the connection after making the call the operation will still complete. You will have to pull the account records to check for an updated aggregation attempt date to know when the refresh is complete.  Note: This service is not available for all Data Access Tiers.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void refreshCustomerAccountsByInstitutionLoginTest() throws ApiException {
        String customerId = null;
        String institutionLoginId = null;
        CustomerAccounts response = api.refreshCustomerAccountsByInstitutionLogin(customerId, institutionLoginId);
        // TODO: test validations
    }

    /**
     * Refresh Customer Account by Institution Login ID for Data Access Tiers
     *
     * Refresh account and transaction data for all accounts associated with a given &#39;institutionLoginId&#x60; with a connection to the institution. Client apps are not permitted to automate calls to the Refresh services. Active accounts are automatically refreshed by Finicity once per day.  Apps may call Refresh services for a specific customer when there is a specific business case for the need of data that is up to date as of the moment. Please discuss with your account manager and systems engineer for further clarification.  Note: This service will be used for Data Access Tiers ASD, AFD and ATD.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void refreshCustomerAccountsByInstitutionLoginV2Test() throws ApiException {
        String customerId = null;
        String institutionLoginId = null;
        api.refreshCustomerAccountsByInstitutionLoginV2(customerId, institutionLoginId);
        // TODO: test validations
    }

    /**
     * Refresh Customer Accounts for Data Access Tiers
     *
     * Refresh account and transaction data for all accounts associated with the  given &#x60;customerId&#x60; with a connection to the institution.  Client apps are not permitted to automate calls to the Refresh services. Active accounts are automatically refreshed by Finicity once per day. Apps may call Refresh services for a specific customer when there is a specific business case for the need of data that is up to date as of the moment. Please discuss with your account manager and systems engineer for further clarification.  Note: This service will be used for Data Access Tiers ASD, AFD and ATD.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void refreshCustomerAccountsV2Test() throws ApiException {
        String customerId = null;
        api.refreshCustomerAccountsV2(customerId);
        // TODO: test validations
    }

}
