/*
 * Open Banking
 * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.openbanking.client.api;

import com.mastercard.openbanking.client.ApiException;
import com.mastercard.openbanking.client.model.AnalyticsReportAck;
import com.mastercard.openbanking.client.model.AnalyticsReportConstraints;
import com.mastercard.openbanking.client.model.BalanceAndCashFlowAnalyticsReportConstraints;
import com.mastercard.openbanking.client.model.ErrorMessage;
import java.io.File;
import com.mastercard.openbanking.client.model.ObbAnalyticsReport;
import com.mastercard.openbanking.client.model.ObbAnalyticsReportAck;
import com.mastercard.openbanking.client.model.ObbErrorMessage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BalanceAnalyticsApi
 */
@Disabled
public class BalanceAnalyticsApiTest {

    private final BalanceAnalyticsApi api = new BalanceAnalyticsApi();

    /**
     * Generate Balance Analytics
     *
     * Balance Analytics for Business analyzes bank balances over time to report metrics and identify behavior that may indicate risk.  Calculated metrics include: * Current/available account balances * Minimum/maximum/average account balances over the requested time   period and broken down by month  * Daily ending balance of accounts for each day in the requested time   period  * Propensity of the customer&#39;s account balances to increase week over   week  * Number of days in the requested time period ending with a negative   balance   This version of the API is intended for piloting and integration testing your application with the Balance Analytics product. It does not adhere to FCRA requirements, and should not be used for production/lending purposes. See _Generate Balance Analytics - FCRA_ for the FCRA compliant version of this API.  A successful call to this API will generate analytics and store a report within Finicity. The report can be retrieved via _Get Balance Analytics Report_ (operation: _GetObbAnalyticsReport_).  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateBalanceAnalyticsTest() throws ApiException {
        String customerId = null;
        BalanceAndCashFlowAnalyticsReportConstraints balanceAndCashFlowAnalyticsReportConstraints = null;
        String referenceNumber = null;
        ObbAnalyticsReportAck response = api.generateBalanceAnalytics(customerId, balanceAndCashFlowAnalyticsReportConstraints, referenceNumber);
        // TODO: test validations
    }

    /**
     * Generate Balance Analytics - FCRA
     *
     * Balance Analytics for Business analyzes bank balances over time to report metrics and identify behavior that may indicate risk.  Calculated metrics include: * Current/available account balances * Minimum/maximum/average account balances over the requested time   period and broken down by month  * Daily ending balance of accounts for each day in the requested time   period  * Propensity of the customer&#39;s account balances to increase week over   week  * Number of days in the requested time period ending with a negative   balance   This version of the API is intended for production use. It maintains and enforces all compliance with FCRA rules and requirements.  *Note:* this is a premium service, billable per every successful API call for non-testing customers.  A successful call to this API will generate analytics and store a report within Finicity. The report can be retrieved via _Get Balance Analytics Report - FCRA_ (operation: _GetObbAnalyticsReportFCRA_).  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateBalanceAnalyticsFcraTest() throws ApiException {
        String customerId = null;
        BalanceAndCashFlowAnalyticsReportConstraints balanceAndCashFlowAnalyticsReportConstraints = null;
        String referenceNumber = null;
        ObbAnalyticsReportAck response = api.generateBalanceAnalyticsFcra(customerId, balanceAndCashFlowAnalyticsReportConstraints, referenceNumber);
        // TODO: test validations
    }

    /**
     * Generate Balance Analytics Report - Personal/Business
     *
     * Generate a Balance Analytics Report for a given customer. This service retrieves up to two years of transaction history from connected accounts.  Balance  Analytics analyzes bank balances over time to report metrics and identify behavior that may indicate risk.  Before calling this API, A consumer or business may need to be created for the given customer ID based on the user type (see Consumer/Business APIs).  If no account type of checking or savings is found, the service will return HTTP 400 Bad Request.  This is a premium service, billable per every successful API call for non-testing customers. A successful call to this API will generate analytics report which can be retrieved via Get Report by Customer or Get Report by Consumer.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateBalanceAnalyticsReportTest() throws ApiException {
        String customerId = null;
        String userType = null;
        AnalyticsReportConstraints analyticsReportConstraints = null;
        String callbackUrl = null;
        AnalyticsReportAck response = api.generateBalanceAnalyticsReport(customerId, userType, analyticsReportConstraints, callbackUrl);
        // TODO: test validations
    }

    /**
     * Get OBB Analytics Report
     *
     * Retrieve the report saved by _Generate Balance Analytics_, _Generate Cash Flow Analytics_, or _Generate Payment History_. Requires the report ID generated by the previous call.  Report data can either be retrieved as a JSON document or a PDF file.  To specify the format required, set the _Accept request header_ to either **application/json** or **application/pdf**. If neither is set, the report format will be returned as a JSON document.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getObbAnalyticsReportTest() throws ApiException {
        String obbReportId = null;
        ObbAnalyticsReport response = api.getObbAnalyticsReport(obbReportId);
        // TODO: test validations
    }

    /**
     * Get OBB Analytics Report - FCRA
     *
     * Retrieve the report saved by _Generate Balance Analytics - FCRA_, _Generate Cash Flow Analytics - FCRA_, or _Generate Payment History - FCRA_. Requires the report ID generated by the previous call.  Report data can either be retrieved as a JSON document or a PDF file.  To specify the format required, set the _Accept request header_ to either **application/json** or **application/pdf**. If neither is set, the report format will be returned as a JSON document.  *Note:* this is a premium service, billable per every successful API call for non-testing customers.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getObbAnalyticsReportFcraTest() throws ApiException {
        String obbReportId = null;
        String purpose = null;
        ObbAnalyticsReport response = api.getObbAnalyticsReportFcra(obbReportId, purpose);
        // TODO: test validations
    }

}
