/*
 * Open Banking
 * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.openbanking.client.api;

import com.mastercard.openbanking.client.ApiException;
import com.mastercard.openbanking.client.model.CashFlowReportAck;
import com.mastercard.openbanking.client.model.CashFlowReportConstraints;
import com.mastercard.openbanking.client.model.ErrorMessage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CashFlowApi
 */
@Disabled
public class CashFlowApiTest {

    private final CashFlowApi api = new CashFlowApi();

    /**
     * Generate Cash Flow Report - Business
     *
     * Generate a Cash Flow Report (Business) report for all checking and savings under the given customer. This service retrieves up to two years of transaction history for the given account. It then uses this information to generate the CFR report. A consumer is not required to generate this report.  This report is not provided under FCRA rules, and this report is not available in the Finicity Consumer Portal for the borrower to view.  If no account type of checking or savings is found, the service will return HTTP 400 Bad Request.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateCashFlowBusinessReportTest() throws ApiException {
        String customerId = null;
        CashFlowReportConstraints cashFlowReportConstraints = null;
        String callbackUrl = null;
        CashFlowReportAck response = api.generateCashFlowBusinessReport(customerId, cashFlowReportConstraints, callbackUrl);
        // TODO: test validations
    }

    /**
     * Generate Cash Flow Report - Personal
     *
     * Generate a Cash Flow Report (Personal) report for all checking and savings under the given customer. This service retrieves up to two years of transaction history for the given account. It then uses this information to generate the CFR report.  This report is provided under FCRA rules, with Finicity acting as the CRA (Consumer Reporting Agency). If an individual account is included in the report - for example, with an individual acting as an personal guarantor on the loan - then this version of the report should be used. In case of an adverse action on the loan where the decision was based on this report, then the borrower can be referred to the [Finicity Consumer Portal](https://consumer.finicityreports.com) where they can view this report and submit a dispute if they feel any information in this report is inaccurate.  Before calling this API, a consumer must be created for the given customer ID (see Consumers APIs).  If no account type of checking or savings is found, the service will return HTTP 400 Bad Request.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateCashFlowPersonalReportTest() throws ApiException {
        String customerId = null;
        CashFlowReportConstraints cashFlowReportConstraints = null;
        String callbackUrl = null;
        CashFlowReportAck response = api.generateCashFlowPersonalReport(customerId, cashFlowReportConstraints, callbackUrl);
        // TODO: test validations
    }

}
