/*
 * Open Banking
 * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.openbanking.client.api;

import com.mastercard.openbanking.client.ApiException;
import com.mastercard.openbanking.client.model.ConnectEmailParameters;
import com.mastercard.openbanking.client.model.ConnectEmailUrl;
import com.mastercard.openbanking.client.model.ConnectJointBorrowerEmailParameters;
import com.mastercard.openbanking.client.model.ConnectJointBorrowerParameters;
import com.mastercard.openbanking.client.model.ConnectParameters;
import com.mastercard.openbanking.client.model.ConnectUrl;
import com.mastercard.openbanking.client.model.ErrorMessage;
import com.mastercard.openbanking.client.model.Experiences;
import com.mastercard.openbanking.client.model.FixConnectParameters;
import com.mastercard.openbanking.client.model.LiteConnectParameters;
import com.mastercard.openbanking.client.model.MicroEntryVerifyRequestParameter;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConnectApi
 */
@Disabled
public class ConnectApiTest {

    private final ConnectApi api = new ConnectApi();

    /**
     * Generate Connect URL
     *
     * Generate a Connect URL link to add within your own applications.  Optional Parameters: * &#x60;experience&#x60;: Configure different customer experiences per Connect session by changing the brand, color, logo, icon, the type of credit decisioning report to generate after the session ends, and more. * &#x60;language&#x60;: By default, the Connect application is in English. You don&#39;t need to pass  this parameter unless you want to translate Connect into one of our supported languages.    * Spanish (United States)   * French (Canada)   MVS Developers: You can pre-populate the consumer&#39;s SSN on the Find employment records page at the beginning of the MVS payroll app. Pass the SSN value for the consumer in the body of the request call.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateConnectUrlTest() throws ApiException {
        ConnectParameters connectParameters = null;
        ConnectUrl response = api.generateConnectUrl(connectParameters);
        // TODO: test validations
    }

    /**
     * Generate Fix Connect URL
     *
     * Use the Connect Fix API when the following conditions occur: * The connection to the user&#39;s financial institution is lost * The user&#39;s credentials were updated (for any number of reasons) * The user&#39;s MFA challenge has expired  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateFixConnectUrlTest() throws ApiException {
        FixConnectParameters fixConnectParameters = null;
        ConnectUrl response = api.generateFixConnectUrl(fixConnectParameters);
        // TODO: test validations
    }

    /**
     * Generate Connect URL - Joint Borrower
     *
     * Same as Connect Full (&#x60;POST /connect/v2/generate&#x60;) but for joint borrowers.  MVS prompts both the primary and joint borrower to enter each of their financial, payroll, and paystub information in the same Connect session.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateJointBorrowerConnectUrlTest() throws ApiException {
        ConnectJointBorrowerParameters connectJointBorrowerParameters = null;
        ConnectUrl response = api.generateJointBorrowerConnectUrl(connectJointBorrowerParameters);
        // TODO: test validations
    }

    /**
     * Generate Lite Connect URL
     *
     * Connect Lite is a variation of Connect Full (&#x60;POST /connect/v2/generate&#x60;), which has a limited set of features. * Sign in, user&#39;s credentials, and Multi-Factor Authentication (MFA) * No user account management  The Connect Web SDK isn&#39;t a requirement when using Connect lite. However, if you want to use the SDK events, routes, and user events, then you must integrate with the Connect Web SDK.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateLiteConnectUrlTest() throws ApiException {
        LiteConnectParameters liteConnectParameters = null;
        ConnectUrl response = api.generateLiteConnectUrl(liteConnectParameters);
        // TODO: test validations
    }

    /**
     * Get Experience IDs
     *
     * Retrieve Connect experiences by application name. Optionally, filter the experiences by product codes.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllExperienceTest() throws ApiException {
        String appName = null;
        List<String> productCode = null;
        List<Experiences> response = api.getAllExperience(appName, productCode);
        // TODO: test validations
    }

    /**
     * Send Connect Email
     *
     * Same as Connect Full (&#x60;POST /connect/v2/generate&#x60;) but send a Connect email to a consumer.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sendConnectEmailTest() throws ApiException {
        ConnectEmailParameters connectEmailParameters = null;
        ConnectEmailUrl response = api.sendConnectEmail(connectEmailParameters);
        // TODO: test validations
    }

    /**
     * Send Connect Email - Joint Borrower
     *
     * Same as Connect Joint Borrower (&#x60;POST /connect/v2/generate/jointBorrower&#x60;) but send a Connect email  to at least one of the joint borrower&#39;s email addresses.  When the consumer opens the email, MVS prompts both the primary and joint borrower to enter each of their financial, payroll, and paystub information in the same Connect session.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sendJointBorrowerConnectEmailTest() throws ApiException {
        ConnectJointBorrowerEmailParameters connectJointBorrowerEmailParameters = null;
        ConnectEmailUrl response = api.sendJointBorrowerConnectEmail(connectJointBorrowerEmailParameters);
        // TODO: test validations
    }

    /**
     * Account Validation Assistant User verification of microdeposits
     *
     * The UI re-engages the consumer to enter two microdeposit amounts found in their account and validates them.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyMicroEntryMicrodepositTest() throws ApiException {
        MicroEntryVerifyRequestParameter microEntryVerifyRequestParameter = null;
        ConnectUrl response = api.verifyMicroEntryMicrodeposit(microEntryVerifyRequestParameter);
        // TODO: test validations
    }

}
