/*
 * Open Banking
 * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.openbanking.client.api;

import com.mastercard.openbanking.client.ApiException;
import com.mastercard.openbanking.client.model.Consumer;
import com.mastercard.openbanking.client.model.ConsumerUpdate;
import com.mastercard.openbanking.client.model.CreatedConsumer;
import com.mastercard.openbanking.client.model.ErrorMessage;
import com.mastercard.openbanking.client.model.NewConsumer;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConsumersApi
 */
@Disabled
public class ConsumersApiTest {

    private final ConsumersApi api = new ConsumersApi();

    /**
     * Create Consumer
     *
     * Create a consumer record associated with the given customer. A consumer persists as the owner of any reports that are generated, even after the original customer is deleted from the system.  A consumer must be created for the given customer before calling any of the Generate Report services.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createConsumerTest() throws ApiException {
        String customerId = null;
        NewConsumer newConsumer = null;
        CreatedConsumer response = api.createConsumer(customerId, newConsumer);
        // TODO: test validations
    }

    /**
     * Get Consumer by ID
     *
     * Get the details of a consumer record by consumer ID.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getConsumerTest() throws ApiException {
        String consumerId = null;
        Consumer response = api.getConsumer(consumerId);
        // TODO: test validations
    }

    /**
     * Get Consumer For Customer
     *
     * Get the details of a consumer record by customer ID.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getConsumerForCustomerTest() throws ApiException {
        String customerId = null;
        Consumer response = api.getConsumerForCustomer(customerId);
        // TODO: test validations
    }

    /**
     * Modify Consumer by ID
     *
     * Modify an existing consumer. All fields are required for a consumer record, but individual fields for this call are optional because fields that are not specified will be left unchanged.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void modifyConsumerTest() throws ApiException {
        String consumerId = null;
        ConsumerUpdate consumerUpdate = null;
        api.modifyConsumer(consumerId, consumerUpdate);
        // TODO: test validations
    }

}
