/*
 * Open Banking
 * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.openbanking.client.api;

import com.mastercard.openbanking.client.ApiException;
import com.mastercard.openbanking.client.model.CreatedCustomer;
import com.mastercard.openbanking.client.model.CustomerUpdate;
import com.mastercard.openbanking.client.model.CustomerWithAppData;
import com.mastercard.openbanking.client.model.Customers;
import com.mastercard.openbanking.client.model.ErrorMessage;
import com.mastercard.openbanking.client.model.GetCustomer200Response;
import com.mastercard.openbanking.client.model.NewCustomer;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CustomersApi
 */
@Disabled
public class CustomersApiTest {

    private final CustomersApi api = new CustomersApi();

    /**
     * Add Customer
     *
     * Enroll an active customer, which is the actual owner of one or more real-world accounts. This is a billable customer.  Active customers must use the \&quot;FinBank Billable\&quot; profiles for testing purposes.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addCustomerTest() throws ApiException {
        NewCustomer newCustomer = null;
        CreatedCustomer response = api.addCustomer(newCustomer);
        // TODO: test validations
    }

    /**
     * Add Testing Customer
     *
     * Enroll a testing customer (Test Drive accounts).  For using testing customers with FinBank OAuth, you must register a test application with your systems engineer or account manager. Then, use that testing &#x60;applicationId&#x60; when creating testing customers.  Testing Customers can access FinBank profiles (except \&quot;FinBank Billable\&quot; profiles), and cannot access live financial institutions.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addTestingCustomerTest() throws ApiException {
        NewCustomer newCustomer = null;
        CreatedCustomer response = api.addTestingCustomer(newCustomer);
        // TODO: test validations
    }

    /**
     * Delete Customer by ID
     *
     * Completely remove a customer from the system. This will remove the customer and all associated accounts and transactions.  ⚠️ Use this service carefully! It will not pause for confirmation before performing the operation!  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteCustomerTest() throws ApiException {
        String customerId = null;
        api.deleteCustomer(customerId);
        // TODO: test validations
    }

    /**
     * Get Customer by ID
     *
     * Retrieve a customer by ID.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCustomerTest() throws ApiException {
        String customerId = null;
        GetCustomer200Response response = api.getCustomer(customerId);
        // TODO: test validations
    }

    /**
     * Get Customer With App Data by ID
     *
     * Retrieve a customer along with additional details about the OAuth application.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCustomerWithAppDataTest() throws ApiException {
        String customerId = null;
        CustomerWithAppData response = api.getCustomerWithAppData(customerId);
        // TODO: test validations
    }

    /**
     * Get Customers
     *
     * Find all customers enrolled by the current partner, where the search text is found in the customer&#39;s username or any combination of &#x60;firstName&#x60; and &#x60;lastName&#x60; fields. If no search text is provided, all customers will be returned.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCustomersTest() throws ApiException {
        String username = null;
        String type = null;
        String search = null;
        Integer start = null;
        Integer limit = null;
        Customers response = api.getCustomers(username, type, search, start, limit);
        // TODO: test validations
    }

    /**
     * Modify Customer by ID
     *
     * Modify an enrolled customer by ID.  You must specify either &#x60;firstName&#x60;, &#x60;lastName&#x60;, or both in the request.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void modifyCustomerTest() throws ApiException {
        String customerId = null;
        CustomerUpdate customerUpdate = null;
        api.modifyCustomer(customerId, customerUpdate);
        // TODO: test validations
    }

}
