/*
 * Open Banking
 * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.openbanking.client.api;

import com.mastercard.openbanking.client.ApiException;
import com.mastercard.openbanking.client.model.BrandingWrapper;
import com.mastercard.openbanking.client.model.CertifiedInstitutions;
import com.mastercard.openbanking.client.model.ErrorMessage;
import com.mastercard.openbanking.client.model.InstitutionWrapper;
import com.mastercard.openbanking.client.model.Institutions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InstitutionsApi
 */
@Disabled
public class InstitutionsApiTest {

    private final InstitutionsApi api = new InstitutionsApi();

    /**
     * Get Certified Institutions
     *
     * Search for financial institutions by certified product.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCertifiedInstitutionsTest() throws ApiException {
        String search = null;
        Integer start = null;
        Integer limit = null;
        String type = null;
        List<String> supportedCountries = null;
        CertifiedInstitutions response = api.getCertifiedInstitutions(search, start, limit, type, supportedCountries);
        // TODO: test validations
    }

    /**
     * Get Certified Institutions With RSSD
     *
     * Search for certified financial institutions w/RSSD.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCertifiedInstitutionsWithRSSDTest() throws ApiException {
        String search = null;
        Integer start = null;
        Integer limit = null;
        String type = null;
        List<String> supportedCountries = null;
        CertifiedInstitutions response = api.getCertifiedInstitutionsWithRSSD(search, start, limit, type, supportedCountries);
        // TODO: test validations
    }

    /**
     * Get Institution by ID
     *
     * Get financial institution details by ID.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInstitutionTest() throws ApiException {
        Long institutionId = null;
        InstitutionWrapper response = api.getInstitution(institutionId);
        // TODO: test validations
    }

    /**
     * Get Institution Branding by ID
     *
     * Return the branding information for a financial institution.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInstitutionBrandingTest() throws ApiException {
        Long institutionId = null;
        BrandingWrapper response = api.getInstitutionBranding(institutionId);
        // TODO: test validations
    }

    /**
     * Get Institutions
     *
     * Search for financial institutions.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInstitutionsTest() throws ApiException {
        String search = null;
        Integer start = null;
        Integer limit = null;
        String type = null;
        List<String> supportedCountries = null;
        Institutions response = api.getInstitutions(search, start, limit, type, supportedCountries);
        // TODO: test validations
    }

}
