/*
 * Open Banking
 * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.openbanking.client.api;

import com.mastercard.openbanking.client.ApiException;
import com.mastercard.openbanking.client.model.ACHDetails;
import com.mastercard.openbanking.client.model.AccountOwner;
import com.mastercard.openbanking.client.model.AccountOwnerHolders;
import com.mastercard.openbanking.client.model.AvailableBalance;
import com.mastercard.openbanking.client.model.ErrorMessage;
import com.mastercard.openbanking.client.model.LoanPaymentDetails;
import com.mastercard.openbanking.client.model.PaymentInstructions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentsApi
 */
@Disabled
public class PaymentsApiTest {

    private final PaymentsApi api = new PaymentsApi();

    /**
     * Get Account ACH Details
     *
     * Return the real account number and routing number details for an ACH payment.  Note: this is a premium service, billable per every successful API call.  _Supported account types_: \&quot;checking\&quot;, \&quot;savings\&quot;, \&quot;moneyMarket\&quot;, \&quot;cd\&quot;  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAccountACHDetailsTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        ACHDetails response = api.getAccountACHDetails(customerId, accountId);
        // TODO: test validations
    }

    /**
     * Get Account Owner
     *
     * Retrieve the names and addresses of the account owner from a financial institution.  Note: this is a premium service, billable per every successful API call.  This service retrieves account data from the institution. This usually returns quickly, but in some scenarios may take a few minutes to complete. In the event of a timeout condition, retry the call.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAccountOwnerTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        AccountOwner response = api.getAccountOwner(customerId, accountId);
        // TODO: test validations
    }

    /**
     * Get Account Owner Details
     *
     * This service retrieves the account details for an account holder from an institution. The following data objects are available.  * Account holders  * Addresses  * Emails  * Phones  * Documentations  * Identity Insights   Note: The data returned varies from institution to institution as not all of them make the same data available. This is a premium service, billable per each successful API call.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAccountOwnerDetailsTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        Boolean withInsights = null;
        AccountOwnerHolders response = api.getAccountOwnerDetails(customerId, accountId, withInsights);
        // TODO: test validations
    }

    /**
     * Get ACH Account Details
     *
     * Return the real account number and routing number details for an ACH payment along with the supported payment instruction details.  Note: this is a premium service, billable per every successful API call.  _Supported account types_: \&quot;checking\&quot;, \&quot;savings\&quot;, \&quot;moneyMarket\&quot;, \&quot;loan\&quot;  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAccountPaymentInstructionDetailsTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        PaymentInstructions response = api.getAccountPaymentInstructionDetails(customerId, accountId);
        // TODO: test validations
    }

    /**
     * Get Available Balance
     *
     * Retrieve the latest cached available and cleared account balances for a customer. Since we update and store balances throughout the day, this is the most accurate balance information available when a connection to a financial institution is unavailable or when a faster response is needed. Only deposit account types are supported: Checking, Savings, Money Market, and CD.  Note: this is a premium service, billable per every successful API call. Enrollment is required.  _Supported account types_: \&quot;checking\&quot;, \&quot;savings\&quot;, \&quot;moneyMarket\&quot;, \&quot;cd\&quot;  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAvailableBalanceTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        AvailableBalance response = api.getAvailableBalance(customerId, accountId);
        // TODO: test validations
    }

    /**
     * Get Available Balance - Live
     *
     * Retrieve the available and cleared account balances for a single account in real-time directly from a financial institution.  Note: this is a premium service, billable per every successful API call.  _Supported account types_: \&quot;checking\&quot;, \&quot;savings\&quot;, \&quot;moneyMarket\&quot;, \&quot;cd\&quot;  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAvailableBalanceLiveTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        AvailableBalance response = api.getAvailableBalanceLive(customerId, accountId);
        // TODO: test validations
    }

    /**
     * Get Loan Payment Details
     *
     * Return the loan payment details of the customer for a loan-type account.  Note: this is a premium service, billable per every successful API call.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLoanPaymentDetailsTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        LoanPaymentDetails response = api.getLoanPaymentDetails(customerId, accountId);
        // TODO: test validations
    }

}
