/*
 * Open Banking
 * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.openbanking.client.api;

import com.mastercard.openbanking.client.ApiException;
import com.mastercard.openbanking.client.model.ErrorMessage;
import com.mastercard.openbanking.client.model.PortfolioSummary;
import com.mastercard.openbanking.client.model.PortfolioWithConsumerSummary;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PortfoliosApi
 */
@Disabled
public class PortfoliosApiTest {

    private final PortfoliosApi api = new PortfoliosApi();

    /**
     * Get Portfolio by Consumer
     *
     * Return a portfolio of most recently generated reports for each report type for a given consumer. If there are multiple reports that were generated for a report type (VOA, VOI, etc.), only the most recently generated report for the type will be returned.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPortfolioByConsumerTest() throws ApiException {
        String consumerId = null;
        String portfolioId = null;
        PortfolioWithConsumerSummary response = api.getPortfolioByConsumer(consumerId, portfolioId);
        // TODO: test validations
    }

    /**
     * Get Portfolio by Customer
     *
     * Return a portfolio of most recently generated reports for each report type for the given customer. If there are multiple reports that were generated for a report type (VOA, VOI, etc.), only the most recently generated report for the type will be returned.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png) 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPortfolioByCustomerTest() throws ApiException {
        String customerId = null;
        String portfolioId = null;
        PortfolioSummary response = api.getPortfolioByCustomer(customerId, portfolioId);
        // TODO: test validations
    }

}
