/*
 * Open Banking
 * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.17.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.openbanking.client.api;

import com.mastercard.openbanking.client.ApiException;
import com.mastercard.openbanking.client.model.CreatedTestTxPushTransaction;
import com.mastercard.openbanking.client.model.ErrorMessage;
import com.mastercard.openbanking.client.model.TestTxPushTransaction;
import com.mastercard.openbanking.client.model.TxPushSubscriptionParameters;
import com.mastercard.openbanking.client.model.TxPushSubscriptions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TxPushApi
 */
@Disabled
public class TxPushApiTest {

    private final TxPushApi api = new TxPushApi();

    /**
     * Create TxPush Test Transaction
     *
     * Inject a transaction into the transaction list for a testing account. This allows an app to trigger TxPush notifications for the account in order to test the app&#39;s TxPush Listener service. This causes the platform to send one transaction event and one account event (showing that the account balance has changed). This service is only supported for testing accounts.  For additional details on this process, see [TxPush Listener Service](https://developer.mastercard.com/open-banking-us/documentation/products/manage/tx-push/#setting-up-the-txpush-listener-service).  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTxPushTestTransactionTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        TestTxPushTransaction testTxPushTransaction = null;
        CreatedTestTxPushTransaction response = api.createTxPushTestTransaction(customerId, accountId, testTxPushTransaction);
        // TODO: test validations
    }

    /**
     * Delete TxPush Subscription
     *
     * Delete a specific subscription to TxPush notifications for the given account. This could be individual deleting the account or transactions events. No more events will be sent for that specific subscription.  For additional details on this process, see [TxPush Listener Service](https://developer.mastercard.com/open-banking-us/documentation/products/manage/tx-push/#setting-up-the-txpush-listener-service).  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteTxPushSubscriptionTest() throws ApiException {
        String customerId = null;
        Long subscriptionId = null;
        api.deleteTxPushSubscription(customerId, subscriptionId);
        // TODO: test validations
    }

    /**
     * Disable TxPush Notifications
     *
     * Delete all TxPush subscriptions with their notifications for the given account. No more notifications will be sent for account or transaction events.  For additional details on this process, see [TxPush Listener Service](https://developer.mastercard.com/open-banking-us/documentation/products/manage/tx-push/#setting-up-the-txpush-listener-service).  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void disableTxPushNotificationsTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        api.disableTxPushNotifications(customerId, accountId);
        // TODO: test validations
    }

    /**
     * Subscribe to TxPush Notifications
     *
     * Register a client app&#39;s TxPush Listener to receive TxPush notifications related to the given account.  Each call to this service will return two records, one with class account and one with class transaction. Account events are sent when values change in the account&#39;s fields (such as &#x60;balance&#x60; or &#x60;interestRate&#x60;). Transaction events are sent whenever a new transaction is posted for the account. For institutions that do not provide TxPush services, notifications are sent as soon as Finicity finds a new transaction or new account data through regular aggregation processes.  The listener&#39;s URL must be secure (HTTPS) for any real-world account. In addition, the client&#39;s TxPush Listener will need to be verified. HTTP and HTTPS connections are only allowed on the standard ports 80 (HTTP) and 443 (HTTPS). The use of other ports will result with the call failing.  For additional details on this process, see [TxPush Listener Service](https://developer.mastercard.com/open-banking-us/documentation/products/manage/tx-push/#setting-up-the-txpush-listener-service).  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void subscribeToTxPushNotificationsTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        TxPushSubscriptionParameters txPushSubscriptionParameters = null;
        TxPushSubscriptions response = api.subscribeToTxPushNotifications(customerId, accountId, txPushSubscriptionParameters);
        // TODO: test validations
    }

}
