// /*
//  * Open Banking
//  * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
//  *
//  * The version of the OpenAPI document: 1.21.3
//  * Contact: apisupport@mastercard.com
//  *
//  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
//  * https://openapi-generator.tech
//  * Do not edit the class manually.
//  */


package com.mastercard.openbanking.client.api;

// import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
// import static org.junit.jupiter.api.Assertions.assertEquals;
// import static org.junit.jupiter.api.Assertions.assertNotNull;
// import java.io.IOException;
// import org.junit.jupiter.api.MethodOrderer;
// import org.junit.jupiter.api.Order;
// import org.junit.jupiter.api.Test;
// import org.junit.jupiter.api.TestMethodOrder;
// import com.google.gson.JsonObject;
// import com.mastercard.openbanking.client.ApiException;
// import com.mastercard.openbanking.client.model.EventStatusUpdate;
// import com.mastercard.openbanking.client.model.ListAvailableWebhookSubscriptionEvents200Response;
// import com.mastercard.openbanking.client.model.Subscription;
// import com.mastercard.openbanking.client.model.SubscriptionDetail;
// import com.mastercard.openbanking.client.model.Subscriptions;
// import com.mastercard.openbanking.client.model.WebhookEvent;
// import com.mastercard.openbanking.client.test.BaseTest;
// import com.mastercard.openbanking.client.test.ModelFactory;
// /**
//  * API tests for WebhookSubscriptionApi
//  */

// @TestMethodOrder(MethodOrderer.OrderAnnotation.class)
// class WebhookSubscriptionApiTest extends BaseTest {
//
//     private final WebhookSubscriptionApi api = new WebhookSubscriptionApi();
//     private static String subscriptionId;
//     private static String webhookEventId;

     
//     /**
//      * Create Webhook Subscription
//      *
//      * Creates a new webhook subscription for receiving event notifications. You can specify the URL for receiving notifications and select the events to subscribe to, including any conditions for filtering. Each partner can have multiple subscriptions, and each subscription can cover multiple events. The API supports URL overrides at the event level, ensuring that each subscription is tailored to specific events and their respective requirements.   _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
//      *
//      * @throws ApiException if the Api call fails
//      */
//     @Test
//     @Order(1)
//     void createWebhookSubscriptionTest() throws ApiException {
//         Subscription subscription = ModelFactory.newSubscription();
//         String xExternalRequestId = "FIN-REQ-0001";
//         SubscriptionDetail response = api.createWebhookSubscription(subscription, xExternalRequestId);
//         assertNotNull(response);
//         assertNotNull(response.getSubscriptionId());
//         assertNotNull(response.getEvents());
//         subscriptionId = response.getSubscriptionId();
//         webhookEventId = response.getEvents().get(0).getWebhookEventId();      
//     }
    
//     /**
//      * Enable or disable all the webhook event under a given webhook subscription
//      *
//      * Enables or disables all webhook subscription event for partner. Update the  status to either active or inactive. _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
//      *
//      * @throws ApiException if the Api call fails
//      * @throws IOException 
//      */
//     @Test
//     @Order(2)
//     void changeWebhookSubscriptionStatusTest() throws ApiException, IOException {
//         EventStatusUpdate eventStatusUpdate = EventStatusUpdate.fromJson(updateEventStatusBodyReq("active"));
//         String xExternalRequestId = "FIN-REQ-0002";
//         EventStatusUpdate response = api.changeWebhookSubscriptionStatus(subscriptionId, eventStatusUpdate, xExternalRequestId);
//         assertNotNull(response);
//         assertEquals("active", response.getStatus());
//     }
    

//     /**
//      * List Webhook Subscriptions
//      *
//      * Retrieves a list of all webhook subscriptions. The response includes details of each subscription, such as the subscription ID, URL, events, and their conditions. This API provides an overview of all active and inactive subscriptions.   _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
//      *
//      * @throws ApiException if the Api call fails
//      */
//     @Test
//     @Order(3)
//     void listWebhookSubscriptionsTest() throws ApiException {
//         String xExternalRequestId = "FIN-REQ-0003";
//         Integer start = 1;
//         Integer limit = 10;
//         Subscriptions response = api.listWebhookSubscriptions(xExternalRequestId, start, limit);
//         assertNotNull(response);
//     }
    
   
//     /**
//      * Get Webhook Subscription Details
//      *
//      * Retrieves detailed information about a specific webhook subscription using the provided subscription ID. The response includes subscription details such as the events, conditions, and current status.   _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
//      *
//      * @throws ApiException if the Api call fails
//      */
//     @Test
//     @Order(4)
//     void getWebhookSubscriptionByIdTest() throws ApiException {        
//         String xExternalRequestId = "FIN-REQ-0004";
//         SubscriptionDetail response = api.getWebhookSubscriptionById(subscriptionId, xExternalRequestId);
//         assertNotNull(response);
//         assertEquals(3, response.getEvents().size());
//     }
    
//     /**
//      * Test Webhook Subscripton Based on Subscription id
//      *
//      * Test all the webhook event under the given webhook subscription using subscription_id. _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
//      *
//      * @throws ApiException if the Api call fails
//      */
//     @Test
//     @Order(5)
//     void testWebhookSubscriptionTest() throws ApiException {       
//         String xExternalRequestId = "FIN-REQ-0011";;
//         assertDoesNotThrow(() ->api.testWebhookSubscription(subscriptionId, xExternalRequestId));
//     }

//     /**
//      * Test Webhook Subscripton Based on Subscription id &amp; Webhook event id.
//      *
//      * Test the webhook event under the given webhook subscription using subscription_id &amp; webhook event id. _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
//      *
//      * @throws ApiException if the Api call fails
//      */
//     @Test
//     @Order(6)
//     void testWebhookSubscriptionBasedOnEventIdTest() throws ApiException {
//         String xExternalRequestId = "FIN-REQ-0012";
//         assertDoesNotThrow(() -> api.testWebhookSubscriptionBasedOnEventId(subscriptionId, webhookEventId, xExternalRequestId));
//     }


//     /**
//      * Update Webhook Subscription
//      *
//      * Updates an existing webhook subscription with the specified subscription ID. You can modify the subscription URL and the events associated with it.   _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
//      *
//      * @throws ApiException if the Api call fails
//      */
//     @Test
//     @Order(7)
//     void updateWebhookSubscriptionTest() throws ApiException {
//         Subscription subscription = ModelFactory.newSubscription();
//         System.out.println("URL >>>> "+subscription.getUrl());
//         subscription.setUrl("https://www.example1.com");
//         System.out.println("Updated URL >>>> "+subscription.getUrl());
//         String xExternalRequestId = "FIN-REQ-0005";
//         SubscriptionDetail response = api.updateWebhookSubscription(subscriptionId, subscription, xExternalRequestId);
//         assertNotNull(response);
//         assertEquals("https://www.example1.com", response.getUrl());
//     }

//     /**
//      * Update Webhook Subscription Event
//      *
//      * Updates a specific webhook event in a subscription. Use subscription Id and webhook Event Id to identify the event and modify its details.   _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
//      *
//      * @throws ApiException if the Api call fails
//      */
//     @Test
//     @Order(8)
//     void updateWebhookSubscriptionEventTest() throws ApiException {
//         WebhookEvent webhookEvent = ModelFactory.getWebhookEvent();
//         webhookEvent.setUrl("https://example.com");
//         String xExternalRequestId = "FIN-REQ-0006";
//         WebhookEvent response = api.updateWebhookSubscriptionEvent(subscriptionId, webhookEventId, webhookEvent, xExternalRequestId);
//         assertNotNull(response);
//         assertEquals("https://example.com", response.getUrl());
//     }


//     /**
//      * Enable or disable Webhook Subscription Event
//      *
//      * Enables or disables a specific webhook event within a subscription identified by subscription ID and webhook event ID. Update the event&#39;s status to either active or inactive.   _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
//      *
//      * @throws ApiException if the Api call fails
//      * @throws IOException 
//      */
//     @Test
//     @Order(9)
//     void changeWebhookSubscriptionEventStatusTest() throws ApiException, IOException {
//         EventStatusUpdate eventStatusUpdate =  EventStatusUpdate.fromJson(updateEventStatusBodyReq("inactive"));
//         String xExternalRequestId = "FIN-REQ-0007";
//         EventStatusUpdate response = api.changeWebhookSubscriptionEventStatus(subscriptionId, webhookEventId, eventStatusUpdate, xExternalRequestId);
//         assertNotNull(response);
//         assertEquals("inactive", response.getStatus());
//     }



//     /**
//      * List Available Webhook Subscription Events
//      *
//      * Allows partners to retrieve a list of all event subscriptions supported by the Open Banking system.  This endpoint provides information about each subscription, including the webhook URL and associated events, enabling partners to understand all available subscription options.   _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
//      *
//      * @throws ApiException if the Api call fails
//      */
//     @Test
//     @Order(10)
//     void listAvailableWebhookSubscriptionEventsTest() throws ApiException {
//         String xExternalRequestId = "FIN-REQ-0008";
//         ListAvailableWebhookSubscriptionEvents200Response response = api.listAvailableWebhookSubscriptionEvents(xExternalRequestId);
//         assertNotNull(response);
//     }
    
    
//     /**
//      * Delete Webhook Subscription Event
//      *
//      * Deletes a specific webhook event from a subscription identified by subscription Id and webhook Event Id.   _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
//      *
//      * @throws ApiException if the Api call fails
//      */
//     @Test
//     @Order(11)
//     void deleteWebhookSubscriptionEventTest() throws ApiException {
//         String xExternalRequestId = "FIN-REQ-0009";
//         assertDoesNotThrow(() -> api.deleteWebhookSubscriptionEvent(subscriptionId, webhookEventId, xExternalRequestId));
//     }
    
//     /**
//      * Delete Webhook Subscription
//      *
//      * Deletes a subscription specified by its ID. Once deleted, the subscription and its associated events will no longer be active or receive notifications   _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
//      *
//      * @throws ApiException if the Api call fails
//      */
//     @Test
//     @Order(12)
//     void deleteWebhookSubscriptionTest() throws ApiException {
//         String xExternalRequestId = "FIN-REQ-0010";
//         assertDoesNotThrow(() -> api.deleteWebhookSubscription(subscriptionId, xExternalRequestId));
//     }


//
//   private String updateEventStatusBodyReq(String status) {
//     	JsonObject jsonObject = new JsonObject();
//     	jsonObject.addProperty("status", status);
//     	return jsonObject.toString();
//     }
// }
