name: API Client Tests
'on':
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch: null
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: temurin
          cache: maven
      - name: Provision customer
        run: |
          customer_id=$(./bin/setup.sh "${{ secrets.PARTNER_ID }}" "${{ secrets.PARTNER_SECRET }}" "${{ secrets.APP_KEY }}" --no-interaction | grep -oP '(?<=CUSTOMER_ID: )\d+')
          if [ -z "$customer_id" ]; then
            echo "Failed to provision customer_id"
            exit 1
          fi
          echo "CUSTOMER_ID=$customer_id" >> "$GITHUB_ENV
      - name: Run Tests
        timeout-minutes: 30
        run: |
          cd tests
          mvn clean test -DpartnerId=${{ secrets.PARTNER_ID }} -DpartnerSecret=${{ secrets.PARTNER_SECRET }} -DappKey=${{ secrets.APP_KEY }} -DcustomerId="${{env.CUSTOMER_ID}}"
